# CLI tools
brew "make"
brew "git"
brew "mas"
brew "chezmoi"
brew "gh"
brew "age"
brew "gnupg"
brew "pinentry-mac"
brew "dockutil"
brew "python@3.14"
brew "gnu-sed"
brew "gnutls"
brew "go"
brew "go-bindata"
brew "golangci-lint"
brew "helm"
brew "jq"
brew "kustomize"
brew "nmap"
brew "pandoc"
brew "poppler"
brew "pre-commit"
brew "qemu"
brew "tlrc"
brew "tmux"
brew "wget"
brew "wireshark"
brew "yq"
brew "zsh"
brew "zsh-autosuggestions"
brew "derailed/k9s/k9s"
brew "kubernetes-cli"

# Apps
cask "iterm2"
cask "visual-studio-code"
cask "google-chrome"
cask "displaylink"
cask "claude"
cask "insomnia"
cask "utm"


#VS Code extensions d
vscode "anthropic.claude-code"
vscode "chrischinchilla.vscode-pandoc"
vscode "coder.coder-remote"
vscode "docker.docker"
vscode "foxundermoon.shell-format"
vscode "george-alisson.html-preview-vscode"
vscode "github.copilot-chat"
vscode "golang.go"
vscode "hashicorp.terraform"
vscode "james-yu.latex-workshop"
vscode "leodevbro.blockman"
vscode "mathematic.vscode-pdf"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "redhat.vscode-yaml"

# # App Store
# mas "Magnet", id: 441258766
# mas "WhatsApp", id: 310633997
# mas "GoodNotes 5", id: 1444383602
# mas "Microsoft Outlook", id: 985367838